---
title: "218X Assignment 2"
author: "Lisiman Hua"
date: "10/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warnings = F, messages = F )
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)
```

```{r}
smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)
smc_blocks_2010 <- blocks("CA", "San Mateo", year = 2010, progress_bar = F)
```

```{r}
mapview(smc_blocks_2010) + mapview(smc_blocks_2020)
```
It seems 2020 blocks are larger

```{r}
Sys.setenv(CENSUS_KEY="5042355b73b371569968738cfc4f492be94675c1")

smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  ) %>% 
  group_by(block) %>% 
  summarize(
    total_pop_2020 = sum(pop, na.rm = T)
  ) %>% 
  filter(!is.na(total_pop_2020))
```

```{r}
smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P001001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001
  ) %>% 
  group_by(block) %>% 
  summarize(
    total_pop_2010 = sum(pop, na.rm = T)
  ) %>% 
  filter(!is.na(total_pop_2010)) 
```

```{r}
smc_blockgroups <- block_groups("CA", "San Mateo", cb = T, progress_bar = F)
```
```{r}
smc_pop <- 
  smc_pop_2020 %>%
  left_join(
    smc_pop_2010, 
    by = "block"
    ) %>%
  mutate(
    pop_change = total_pop_2020 - total_pop_2010
  ) %>% 
  filter(!is.na(pop_change))
```

```{r}
smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

nfo_pop <- smc_pop %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()
```

```{r}
mapview(nfo_pop, zcol = "pop_change")
```

